### ISSUE TITLE
English translation and/or ability to provide Zimlet translations?

### ISSUE THREAD

**Issue by robert-scheck** [Zimbra-Community/zimbra-zimlet-lifesize#1]
Is there any chance for an English translation of the Zimlet texts, labels etc.? Right now they are only French, and there does not seem to be a structure inside the Zimlet to provide additional translations.

**Comment by ghost** [comment]
please try new version https://github.com/Zimbra-Community/zimbra-zimlet-lifesize/raw/main/fr_cd21_startmeeting.zip
